// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQ2GTja9y60RzO116E0BrP0R8Ua9-fzE',
    appId: '1:177620673540:web:d8a5a93a537a6578c88151',
    messagingSenderId: '177620673540',
    projectId: 'flutter-push-sample-11',
    authDomain: 'flutter-push-sample-11.firebaseapp.com',
    storageBucket: 'flutter-push-sample-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBbE1QI6deW3L4Woimfdf3ETpQIqHjNA',
    appId: '1:177620673540:android:0057e3958f5e6ecfc88151',
    messagingSenderId: '177620673540',
    projectId: 'flutter-push-sample-11',
    storageBucket: 'flutter-push-sample-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZ8vrownfF4Zv5ptt5v8_4tHiW69b5bM',
    appId: '1:177620673540:ios:560546b3fb9871acc88151',
    messagingSenderId: '177620673540',
    projectId: 'flutter-push-sample-11',
    storageBucket: 'flutter-push-sample-11.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZ8vrownfF4Zv5ptt5v8_4tHiW69b5bM',
    appId: '1:177620673540:ios:560546b3fb9871acc88151',
    messagingSenderId: '177620673540',
    projectId: 'flutter-push-sample-11',
    storageBucket: 'flutter-push-sample-11.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQ2GTja9y60RzO116E0BrP0R8Ua9-fzE',
    appId: '1:177620673540:web:504cf4a47279a793c88151',
    messagingSenderId: '177620673540',
    projectId: 'flutter-push-sample-11',
    authDomain: 'flutter-push-sample-11.firebaseapp.com',
    storageBucket: 'flutter-push-sample-11.firebasestorage.app',
  );
}
