// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum WifiStatusApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum WifiConnectionType: Int, CaseIterable {
  case wifi = 0
  case other = 1
  case none = 2
  case unknown = 3
}

/// Wi-Fi network state shared, with a single definition, across all platforms.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WifiStatus: Hashable, CustomStringConvertible {
  /// Whether the Wi-Fi radio is turned on (best effort; iOS cannot report it).
  var isEnabled: Bool
  /// Whether the active network connection is going through Wi-Fi.
  var isConnected: Bool
  var connectionType: WifiConnectionType
  /// Network name. Usually null without extra permissions/entitlements.
  var ssid: String? = nil
  /// Signal strength bucket (0-4). Null when unavailable.
  var signalLevel: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WifiStatus? {
    let isEnabled = pigeonVar_list[0] as! Bool
    let isConnected = pigeonVar_list[1] as! Bool
    let connectionType = pigeonVar_list[2] as! WifiConnectionType
    let ssid: String? = nilOrValue(pigeonVar_list[3])
    let signalLevel: Int64? = nilOrValue(pigeonVar_list[4])

    return WifiStatus(
      isEnabled: isEnabled,
      isConnected: isConnected,
      connectionType: connectionType,
      ssid: ssid,
      signalLevel: signalLevel
    )
  }
  func toList() -> [Any?] {
    return [
      isEnabled,
      isConnected,
      connectionType,
      ssid,
      signalLevel,
    ]
  }
  static func == (lhs: WifiStatus, rhs: WifiStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return WifiStatusApiPigeonInternal.deepEquals(lhs.isEnabled, rhs.isEnabled) && WifiStatusApiPigeonInternal.deepEquals(lhs.isConnected, rhs.isConnected) && WifiStatusApiPigeonInternal.deepEquals(lhs.connectionType, rhs.connectionType) && WifiStatusApiPigeonInternal.deepEquals(lhs.ssid, rhs.ssid) && WifiStatusApiPigeonInternal.deepEquals(lhs.signalLevel, rhs.signalLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WifiStatus")
    WifiStatusApiPigeonInternal.deepHash(value: isEnabled, hasher: &hasher)
    WifiStatusApiPigeonInternal.deepHash(value: isConnected, hasher: &hasher)
    WifiStatusApiPigeonInternal.deepHash(value: connectionType, hasher: &hasher)
    WifiStatusApiPigeonInternal.deepHash(value: ssid, hasher: &hasher)
    WifiStatusApiPigeonInternal.deepHash(value: signalLevel, hasher: &hasher)
  }

  public var description: String {
    return "WifiStatus(isEnabled: \(String(describing: isEnabled)), isConnected: \(String(describing: isConnected)), connectionType: \(String(describing: connectionType)), ssid: \(String(describing: ssid)), signalLevel: \(String(describing: signalLevel)))"
  }
}

private class WifiStatusApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WifiConnectionType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return WifiStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WifiStatusApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WifiConnectionType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WifiStatus {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WifiStatusApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WifiStatusApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WifiStatusApiPigeonCodecWriter(data: data)
  }
}

class WifiStatusApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WifiStatusApiPigeonCodec(readerWriter: WifiStatusApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WifiStatusApi {
  func getWifiStatus(completion: @escaping (Result<WifiStatus, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WifiStatusApiSetup {
  static var codec: FlutterStandardMessageCodec { WifiStatusApiPigeonCodec.shared }
  /// Sets up an instance of `WifiStatusApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WifiStatusApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getWifiStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_and_native_samples.WifiStatusApi.getWifiStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWifiStatusChannel.setMessageHandler { _, reply in
        api.getWifiStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getWifiStatusChannel.setMessageHandler(nil)
    }
  }
}
