// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_and_native_samples

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WifiStatusApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class WifiConnectionType(val raw: Int) {
  WIFI(0),
  OTHER(1),
  NONE(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): WifiConnectionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Wi-Fi network state shared, with a single definition, across all platforms.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WifiStatus (
  /** Whether the Wi-Fi radio is turned on (best effort; iOS cannot report it). */
  val isEnabled: Boolean,
  /** Whether the active network connection is going through Wi-Fi. */
  val isConnected: Boolean,
  val connectionType: WifiConnectionType,
  /** Network name. Usually null without extra permissions/entitlements. */
  val ssid: String? = null,
  /** Signal strength bucket (0-4). Null when unavailable. */
  val signalLevel: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WifiStatus {
      val isEnabled = pigeonVar_list[0] as Boolean
      val isConnected = pigeonVar_list[1] as Boolean
      val connectionType = pigeonVar_list[2] as WifiConnectionType
      val ssid = pigeonVar_list[3] as String?
      val signalLevel = pigeonVar_list[4] as Long?
      return WifiStatus(isEnabled, isConnected, connectionType, ssid, signalLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isEnabled,
      isConnected,
      connectionType,
      ssid,
      signalLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WifiStatus
    return WifiStatusApiPigeonUtils.deepEquals(this.isEnabled, other.isEnabled) && WifiStatusApiPigeonUtils.deepEquals(this.isConnected, other.isConnected) && WifiStatusApiPigeonUtils.deepEquals(this.connectionType, other.connectionType) && WifiStatusApiPigeonUtils.deepEquals(this.ssid, other.ssid) && WifiStatusApiPigeonUtils.deepEquals(this.signalLevel, other.signalLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WifiStatusApiPigeonUtils.deepHash(this.isEnabled)
    result = 31 * result + WifiStatusApiPigeonUtils.deepHash(this.isConnected)
    result = 31 * result + WifiStatusApiPigeonUtils.deepHash(this.connectionType)
    result = 31 * result + WifiStatusApiPigeonUtils.deepHash(this.ssid)
    result = 31 * result + WifiStatusApiPigeonUtils.deepHash(this.signalLevel)
    return result
  }
  override fun toString(): String {
    return "WifiStatus(isEnabled=$isEnabled, isConnected=$isConnected, connectionType=$connectionType, ssid=$ssid, signalLevel=$signalLevel)"
  }
}
private open class WifiStatusApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WifiConnectionType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WifiStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WifiConnectionType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WifiStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WifiStatusApi {
  fun getWifiStatus(callback: (Result<WifiStatus>) -> Unit)

  companion object {
    /** The codec used by WifiStatusApi. */
    val codec: MessageCodec<Any?> by lazy {
      WifiStatusApiPigeonCodec()
    }
    /** Sets up an instance of `WifiStatusApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WifiStatusApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_and_native_samples.WifiStatusApi.getWifiStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getWifiStatus{ result: Result<WifiStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WifiStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WifiStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
