import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

/// Replace this file with the one generated by `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQvP0B_0GdahZ4vDsQCGvHZrv10lzkSA',
    appId: '1:56066682730:android:8570cb7a481e5c2332ff13',
    messagingSenderId: '56066682730',
    projectId: 'authors-e9382',
    storageBucket: 'authors-e9382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzGyB7YWwU5b5ZEbGjUOUYIQTgmplO_g',
    appId: '1:56066682730:ios:04d05d4143a2ce7932ff13',
    messagingSenderId: '56066682730',
    projectId: 'authors-e9382',
    storageBucket: 'authors-e9382.firebasestorage.app',
    androidClientId: '56066682730-raang96u8iv3cr9fljgk6kap7h2av5jj.apps.googleusercontent.com',
    iosClientId: '56066682730-u2djmd2pdd1qtl4phl3l1msaj5hs8udc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorsCollection',
  );

}