import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../pigeon/wifi_status.g.dart';

/// Reads Wi-Fi state through a Pigeon-generated, type-safe host API.
class WifiStatusScreen extends StatefulWidget {
  const WifiStatusScreen({super.key, this.api});

  final WifiStatusApi? api;

  @override
  State<WifiStatusScreen> createState() => _WifiStatusScreenState();
}

class _WifiStatusScreenState extends State<WifiStatusScreen> {
  late final WifiStatusApi _api = widget.api ?? WifiStatusApi();

  WifiStatus? _status;
  String? _errorMessage;
  bool _loading = false;

  Future<void> _refresh() async {
    setState(() {
      _loading = true;
      _errorMessage = null;
    });

    try {
      // The WifiStatus type is generated by Pigeon; no manual Map parsing here.
      final status = await _api.getWifiStatus();
      if (!mounted) {
        return;
      }
      setState(() {
        _status = status;
      });
    } on PlatformException catch (error) {
      if (!mounted) {
        return;
      }
      setState(() {
        _errorMessage =
            'Platform error while reading Wi-Fi: ${error.message ?? error.code}';
      });
    } catch (error) {
      if (!mounted) {
        return;
      }
      setState(() {
        _errorMessage = 'Unexpected error while reading Wi-Fi: $error';
      });
    } finally {
      if (mounted) {
        setState(() {
          _loading = false;
        });
      }
    }
  }

  String get _connectionTypeLabel {
    return switch (_status?.connectionType) {
      WifiConnectionType.wifi => 'Wi-Fi',
      WifiConnectionType.other => 'Other (cellular/ethernet)',
      WifiConnectionType.none => 'None',
      WifiConnectionType.unknown => 'Unknown',
      null => '',
    };
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final status = _status;

    return Scaffold(
      appBar: AppBar(title: const Text('Pigeon sample')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Status', style: theme.textTheme.titleLarge),
                  const SizedBox(height: 12),
                  _InfoRow(
                    label: 'Platform',
                    value: defaultTargetPlatform.name,
                  ),
                  _InfoRow(
                    label: 'Wi-Fi enabled',
                    value: status == null ? '' : '${status.isEnabled}',
                  ),
                  _InfoRow(
                    label: 'Connected via Wi-Fi',
                    value: status == null ? '' : '${status.isConnected}',
                  ),
                  _InfoRow(
                    label: 'Connection type',
                    value: _connectionTypeLabel,
                  ),
                  _InfoRow(
                    label: 'SSID',
                    value: status == null ? '' : (status.ssid ?? 'Not exposed'),
                  ),
                  _InfoRow(
                    label: 'Signal level',
                    value: status == null
                        ? ''
                        : (status.signalLevel?.toString() ?? 'Not exposed'),
                  ),
                  if (_errorMessage != null) ...[
                    const SizedBox(height: 8),
                    Text(
                      _errorMessage!,
                      style: TextStyle(color: theme.colorScheme.error),
                    ),
                  ],
                  const SizedBox(height: 16),
                  Row(
                    children: [
                      FilledButton(
                        onPressed: _loading ? null : _refresh,
                        child: const Text('Refresh Wi-Fi status'),
                      ),
                      if (_loading) ...[
                        const SizedBox(width: 16),
                        const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        ),
                      ],
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _InfoRow extends StatelessWidget {
  const _InfoRow({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 160,
            child: Text(
              label,
              style: Theme.of(
                context,
              ).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600),
            ),
          ),
          Expanded(child: Text(value)),
        ],
      ),
    );
  }
}
